runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest

handlers:
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /.*
  script: main.app
